import type { Metadata } from "next";
import "./styles/index.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-dvh w-dvh overflow-hidden antialiased theme-light font-ds-family-primary`}
    >
      <body className="h-full w-full overflow-hidden bg-ds-cl-bg-base-default">
        {children}
      </body>
    </html>
  );
}
